# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sentiment-api'
    static_configs:
      - targets: ['sentiment-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s